image: thecodingmachine/php:7.2-v1-apache

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}


test:
  stage: test
  cache:
    paths:
      - vendor
  script:
    - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests

